site_name: Container Shipment EDA User Interface
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc-ui
nav:
  - Introduction: index.md
  - Build and run: build-run.md
  - Demonstration script: https://ibm-cloud-architecture.github.io/refarch-kc/demo/readme/


theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences