apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kc-ui.fullname" . }}
  labels:
    app: {{ template "kc-ui.name" . }}
    chart: {{ template "kc-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kc-ui.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kc-ui.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.servicePort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds}}
        ports:
        - containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: KAFKA_ENV
            value: "{{ .Values.eventstreams.env }}"
          - name: KAFKA_BROKERS
            value: "{{ .Values.eventstreams.brokers }}"
          {{if or (eq .Values.eventstreams.env "IBMCLOUD") (eq .Values.eventstreams.env "ICP")}}
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
          - name: APPLICATION_NAME
            value: "{{ .Release.Name }}"
          - name: FLEETMS_SERVICE_SERVICE_HOST
            value: "fleetms-service"
          - name: FLEETMS_SERVICE_SERVICE_PORT
            value: "9080"
          - name: ORDERCOMMANDMS_SERVICE_SERVICE_HOST
            value: "ordercommandms-service"
          - name: ORDERCOMMANDMS_SERVICE_SERVICE_PORT_HTTP
            value: "9080"
          - name: ORDERQUERYMS_SERVICE_SERVICE_HOST
            value: "orderqueryms-service"
          - name: ORDERQUERYMS_SERVICE_SERVICE_PORT_HTTP
            value: "9080"
          - name: VOYAGEMS_SERVICE_SERVICE_HOST
            value: "voyagesms-service"
          - name: VOYAGESMS_SERVICE_SERVICE_PORT_HTTP
            value: "3000"
          {{else}}
          - name: FLEET_MS_URL
            value: "http://fleetms-service:9080/fleetms"
          - name: ORDER_MS_URL
            value: "http://ordercommandms-service:10080/orders"
          - name: ORDER_QUERY_MS_URL
            value: "http://orderqueryms-service:11080/orders"
          - name: VOYAGE_MS_URL
            value: "http://voyagesms-service:3100"
          {{end}}
          {{if or (eq .Values.eventstreams.env "IBMCLOUD") (eq .Values.eventstreams.env "ICP")}}
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: eventstreams-apikey
                key: binding
          {{end}}
{{- if .Values.generatedBindings.enabled }}
{{.Files.Get "bindings.yaml" | indent 10 }}
{{- end }}
