apiVersion: v1
kind: Service
metadata:
  name: {{ template "kc-ui.fullname" . }}
  labels:
    app: {{ template "kc-ui.name" . }}
    chart: {{ template "kc-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
    nodePort: {{ .Values.service.nodePort }}
  - name: https
    port: {{ .Values.service.servicePortHttps }}
  selector:
    app: {{ template "kc-ui.name" . }}
    release: {{ .Release.Name }}
