name: Build & push image for 'kc-ui'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'chart/**'
      - 'docs/**'
env:
  WORKDIR: .
  DOCKERFILE: Dockerfile
  IMAGE_NAME: ibmcase/kcontainer-ui
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump Versions
      uses: remorses/bump-version@js
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        version_file: ./VERSION
    - name: Build the Docker image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        export TAG_VERSION=$(cat VERSION)
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${TAG_VERSION}
        docker tag ${IMAGE_NAME}:${TAG_VERSION} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
